deploy:
  provider: heroku
  api_key:
    secure: IGGuA5DhrJwQCLyB1zPJXMP8SuRfSKnJsrfIv/qRmHicx99oX2AfYKKSgT1XTSz7qB+2O3fb2cmEtua5qWkRPpQ6MW6kBpCoBRqy2yPfqCgRzHKcTbUZdGGMsOYBIOzH1/YyWOasD58bJs8Vxi1dkLPzzWJu5iXbchLLrBPCYxcqHFoBBMhrnrCwY3KB0LY8QhaoWEbgl6VlKyqgQ461OoYRoA3T7XHZLaNKQxnvZN16eUU2gbHBnYfgCcA7zB0mpfgtitz6YjqJbip2e3XWN/598Si1sriSJRpSFTV3TFpPFuCmHSbRFVzpAN622dtZw7CBFEVkHIb3GFcW02nU0rJcE3LX+GcusoRdtKrdwNrUFomUsTn9r1FlSCIyHX3i8tE2rUs6TNwJikWDBRTFo6/h94EYOhuuDuhylg4KVpREbV3bJH8y8VEfrdCt1jy07rESjZ77YSpcsk3FCFkzDehsuFoY+n+TU7Putr57rjwBJf5Cv1+VcVH3z/DSQt2NgawW1LpAGO6xwuEvwr/oDUgo8js+/ZYF6UuCvNGPXYMiHb25d0EoMeO1BAYyun1r3SKVTw/fxFKy6/NX3jFqjLN4QHmAguOCyx4xd2qPlFQJJlBRdat3lh+uj7JOtTJcB6kNSx58RJj3EHyECMgaQAnEoB4sa1AwOxvw6KByHG8=
  app: hooshome
language: python
python:
- 3.6.1
install:
- pip install -r requirements-build.txt
- pip install social-auth-app-django
script:
- python manage.py test home
