deploy:
  provider: heroku
  api_key:
    secure: a555cb9d-fdd4-4efc-bd48-e5c24904fe29
  app: hooshome
language: python
python:
- 3.6.1
install:
- pip install -r requirements-build.txt
- pip install social-auth-app-django
script:
- python manage.py test home
