# Generated by Django 2.1.7 on 2019-03-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bedsbaths',
            field=models.CharField(default='2B/2B', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='ratings',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
