# Generated by Django 2.1.7 on 2019-03-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190318_2112'),
        ('home', '0002_auto_20190318_1728'),
    ]

    operations = [
    ]
