# Generated by Django 2.1.7 on 2019-03-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_merge_20190321_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bedsbaths',
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='Charlottesville', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='zip',
            field=models.CharField(default=22903, max_length=12, verbose_name='ZIP / Postal code'),
        ),
    ]
